### ISSUE TITLE
Doesn't work on MacMini

### ISSUE THREAD

**Issue by andrevenancio** [sp1thas/dropboxignore#10]
I've been waiting for something like this for a very long time. I'm so happy you took the time to implement this. thank you!

However after trying this I keep getting errors.

So I've open Terminal jumped inside my Dropbox folder, and a particular folder inside of that that uses git and has node_modules.

I've tried `dropboxignore ignore ~/Dropbox/test` and it returns "/usr/local/bin/dropboxignore: line 572: realpath: command not found"

Also going inside the folder directly and just typing "dropboxignore ignore ." returns the same error.

Using Mac Mini M1 2020

**Comment by sp1thas** [comment]
Hello @andrevenancio ,

thank you so much for your kind words :) It looks like `realpath` command doesn't exists on your os which is quite unusual. Could you please verify it by running `realpath .` in your terminal?

**Comment by andrevenancio** [comment]
Seems like I dont have it `zsh: command not found: realpath`

**Comment by sp1thas** [comment]
It looks like `realpath` doesn't exists in some platforms, I will implement a fix asap. In the meanwhile, it would be very helpful if you could verify that `readlink -f .` works in your os. Thanks in advance and I will keep you up-to-date.

**Comment by andrevenancio** [comment]
It looks like it works, but that returns a double dash
```bash
readlink -f .
```
response:
```bash
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by sp1thas** [comment]
Should be fixed by the latest release
