### ISSUE TITLE
Command with relative path doesn't work on my Ubuntu 20.04

### ISSUE THREAD

**Issue by haoadoreorange** [sp1thas/dropboxignore#12]
**Describe the bug**
Run whatever the command with relative path returns errror `cat: /usr/local/share/dropboxignore/VERSION.txt: No such file or directory`

**To Reproduce**
1. Just run with relative path

**Screenshots**
![image](https://user-images.githubusercontent.com/22086462/111724739-2976d100-883c-11eb-9404-5232a0f024ee.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version v0.1.4-beta

**Additional context**
snap package

**Comment by haoadoreorange** [comment]
Oh sorry, it seems to work, it just raise some error about `cat`, there is no error if installing manually, this is snap-related ?

**Comment by sp1thas** [comment]
Hello @babyadoresorange thanks for your feedback, `VERSION.txt` is deprecated and it looks like snap is outdated. I will release a new version asap and I will fix this. I will keep this issue open until is resolved.

**Comment by sp1thas** [comment]
Latest snap release (v0.1.5) resolves this issue.
