### ISSUE TITLE
Installation script should not use wget as a default way to retrieve the dropboxingore

### ISSUE THREAD

**Issue by sp1thas** [sp1thas/dropboxignore#5]
As you can see in the [README.md](https://github.com/sp1thas/dropboxignore/blob/master/README.md) file, there are more than one methods to perform the basic installation. The selected method is not respected by [`install.sh`](https://github.com/sp1thas/dropboxignore/blob/master/utils/install.sh) script because installation script uses `wget` to retrieve the `dropboxignore` shell script.

This should be changed:

 1. `git clone` the whole repo instead of retrieving [`bin/dropboxingore.sh`](https://github.com/sp1thas/dropboxignore/blob/master/bin/dropboxignore.sh) script using `wget`.
 2.  Remove cloned repo after the installation.
 3. Mention on [README.md](https://github.com/sp1thas/dropboxignore/blob/master/README.md) file that `git` should be installed in order to install the package using the basic installation way.

**Comment by Drallas** [comment]
I'm looking at it..
Pull request is submitted!

**Comment by Drallas** [comment]
ah i see that's an optional step. :)
