### ISSUE TITLE
Junk characters in CLI output

### ISSUE THREAD

**Issue by asbjornu** [sp1thas/dropboxignore#56]
**Describe the bug**
When using the `dropboxignore` CLI on macOS 13.5.2, I get junk characters such as `\e[34m` sprinkled around in the output. The result from running the command `dropboxignore ignore ./node_modules` for instance, is:

```
usage: realpath [-q] [path ...]
\e[34mTotal number of ignored files: 0 \e[0m
Total number of ignored folders: 1 \e[0m
```

**To Reproduce**
1. Install dropboxignore on macOS
2. Run any dropboxignore command
3. Notice how the output is full of junk characters.

**Expected behavior**
The output should not be full of junk characters.

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Version: 1.2.2

**Comment by sp1thas** [comment]
Thanks for bringing this up @asbjornu ! I just reproduced it in macOS 13.4

Seems `echo` is not the best way to print colored characters. `printf` seems to be a better option. Details can be found [here](https://stackoverflow.com/a/37118992/6779252).

I will fix it asap, in case you are interested to make one more contribution, feel to open a PR with the fix.

**Comment by asbjornu** [comment]
@sp1thas thanks, I've submitted #58.
